version: "3"
services:
  postgres_test_project:
    container_name: postgres_test_project
    restart: always
    image: test_project/postgres
    build: ./postgres
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
